import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";

export interface ForgeManifest {
  projectName: string;
  recipeId: string;
  recipeVersion: string;
}

export interface PublishOptions {
  outputDir: string;
  branch?: string;
  remote?: string;
  title?: string;
  body?: string;
  draft?: boolean;
  push?: boolean;
}

export interface PublishResult {
  outputDir: string;
  branch: string;
  committed: boolean;
  pushed: boolean;
  prUrl?: string;
  instructions: string[];
}

function runGit(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim();
}

function hasGh(): boolean {
  const r = spawnSync("gh", ["--version"], { encoding: "utf8" });
  return r.status === 0;
}

async function readManifest(outputDir: string): Promise<ForgeManifest> {
  const raw = await fs.readFile(path.join(outputDir, "forge.manifest.json"), "utf8");
  const data = JSON.parse(raw) as ForgeManifest;
  if (!data.projectName) {
    throw new Error("forge.manifest.json missing projectName");
  }
  return data;
}

export async function publishForgeOutput(
  options: PublishOptions
): Promise<PublishResult> {
  const outputDir = path.resolve(options.outputDir);
  const manifest = await readManifest(outputDir);
  const branch =
    options.branch ?? `forge/${manifest.projectName}-${Date.now().toString(36)}`;
  const instructions: string[] = [];
  let committed = false;
  let pushed = false;
  let prUrl: string | undefined;

  const gitDir = path.join(outputDir, ".git");
  let isRepo = false;
  try {
    await fs.access(gitDir);
    isRepo = true;
  } catch {
    isRepo = false;
  }

  if (!isRepo) {
    runGit(outputDir, ["init"]);
    runGit(outputDir, ["checkout", "-b", branch]);
    instructions.push(`Initialized git repository on branch ${branch}`);
  } else {
    try {
      runGit(outputDir, ["rev-parse", "--abbrev-ref", "HEAD"]);
      runGit(outputDir, ["checkout", "-B", branch]);
    } catch {
      runGit(outputDir, ["checkout", "-b", branch]);
    }
  }

  runGit(outputDir, ["add", "-A"]);
  const status = runGit(outputDir, ["status", "--porcelain"]);
  if (status) {
    const msg = `forge: ${manifest.recipeId}@${manifest.recipeVersion} — ${manifest.projectName}`;
    runGit(outputDir, ["commit", "-m", msg]);
    committed = true;
  }

  if (options.remote) {
    try {
      runGit(outputDir, ["remote", "get-url", "origin"]);
      runGit(outputDir, ["remote", "set-url", "origin", options.remote]);
    } catch {
      runGit(outputDir, ["remote", "add", "origin", options.remote]);
    }
  }

  if (options.push && options.remote) {
    runGit(outputDir, ["push", "-u", "origin", branch]);
    pushed = true;
    instructions.push(`Pushed branch ${branch} to origin`);

    if (hasGh()) {
      const title =
        options.title ?? `Forge: ${manifest.projectName} (${manifest.recipeId})`;
      const body =
        options.body ??
        `Generated by ProjectForgeAi forge.\n\nRecipe: ${manifest.recipeId}@${manifest.recipeVersion}`;
      const args = [
        "pr",
        "create",
        "--title",
        title,
        "--body",
        body,
        "--head",
        branch,
      ];
      if (options.draft !== false) {
        args.push("--draft");
      }
      const pr = spawnSync("gh", args, { cwd: outputDir, encoding: "utf8" });
      if (pr.status === 0) {
        prUrl = (pr.stdout || "").trim();
        instructions.push(`Opened pull request: ${prUrl}`);
      } else {
        instructions.push(
          `gh pr create failed: ${(pr.stderr || pr.stdout || "").trim()}`,
          "Create a PR manually from your branch."
        );
      }
    } else {
      instructions.push(
        "Install GitHub CLI (gh) and authenticate to open a PR automatically.",
        `Manual: push branch ${branch} and open a PR on GitHub.`
      );
    }
  } else {
    instructions.push(
      "Local git repo ready. To open a PR:",
      `  cd ${outputDir}`,
      options.remote
        ? `  git push -u origin ${branch} && gh pr create --draft`
        : "  git remote add origin <your-repo-url> && git push -u origin <branch>",
    );
  }

  return {
    outputDir,
    branch,
    committed,
    pushed,
    prUrl,
    instructions,
  };
}
